Repository Jovian-Experiments/Jovian-NixOS, pull requests merged in 2023-09, with the labels that each got.

#164 Assorted bumps as of vendor 20230915.1000
  modules/steam/steam.nix
  pkgs/jupiter-hw-support/src.nix
  pkgs/linux-jovian/default.nix
  pkgs/mangohud/default.nix
  pkgs/mangohud/upstream/default.nix
  pkgs/mangohud/upstream/preload-nix-workaround.patch
  pkgs/mesa-radv-jupiter/default.nix
  pkgs/mesa-radv-jupiter/disk_cache-include-dri-driver-path-in-cache-key.patch
  pkgs/steam-jupiter/unwrapped.nix
Labels: 2. priority: 1. high, 2. topic: packaging

#111 modules: Add decky-loader
  modules/decky-loader.nix
  modules/default.nix
  overlay.nix
  pkgs/decky-loader/default.nix
Labels: 2. priority: 2. normal, 2. topic: system integration, 2. topic: packaging

#166 mangohud: 0.6.9.1.r22 -> 0.7.0.rc1.r4
  pkgs/mangohud/default.nix
  pkgs/mangohud/upstream/default.nix
  pkgs/mangohud/upstream/preload-nix-workaround.patch
Labels: 2. priority: 1. high

#165 jupiter-hw-support: 20230908.1 -> 20230918.1
  pkgs/jupiter-hw-support/src.nix
Labels: 2. priority: 2. normal

#154 docs: Add more docs
  CONTRIBUTING.md
  README.md
  docs/FAQ.md
  docs/README.md
  docs/configuration.md
  docs/devices/valve-steam-deck/index.md
  docs/getting-started.md
  docs/in-depth.md
  docs/in-depth/decky-loader.md
  docs/options.md
  docs/steam.md
Labels: 2. topic: documentation, 2. priority: 2. normal

#167 treewide: resholve everything, big refactor gamescope-session
  modules/steam/autostart.nix
  modules/steam/steam.nix
  modules/steamdeck/firmware.nix
  overlay.nix
  pkgs/gamescope-session/default.nix
  pkgs/jovian-greeter/greeter.py
  pkgs/jovian-steam-protocol-handler/default.nix
  pkgs/jovian-stubs/default.nix
  pkgs/jovian-stubs/jupiter-biosupdate
  pkgs/jovian-stubs/pkexec
  pkgs/jovian-stubs/steamos-factory-reset-config
  pkgs/jovian-stubs/steamos-reboot
  pkgs/jovian-stubs/steamos-select-branch
  pkgs/jovian-stubs/steamos-update
  pkgs/jovian-stubs/sudo
  pkgs/jupiter-dock-updater-bin/default.nix
  pkgs/jupiter-fan-control/default.nix
  pkgs/jupiter-hw-support/bios-fwupd.nix
  pkgs/jupiter-hw-support/default.nix
  pkgs/jupiter-hw-support/firmware.nix
  pkgs/jupiter-hw-support/jovian.patch
  pkgs/jupiter-hw-support/polkit-helpers.nix
  pkgs/jupiter-hw-support/src.nix
  pkgs/powerbuttond/default.nix
  pkgs/powerbuttond/jovian.patch
  pkgs/steam-jupiter/fhsenv.nix
  pkgs/steam_notif_daemon/default.nix
  pkgs/steam_notif_daemon/jovian.patch
Labels: 2. priority: 2. normal, 2. topic: system integration
