Repository Jovian-Experiments/Jovian-NixOS, pull requests merged in 2024-10, with the labels that each got.

#332 jovian-documentation: Use pagefind from nixpkgs
  overlay.nix
  pkgs/pagefind/default.nix
Labels: 2. topic: documentation, 2. priority: 2. normal

#435 jovian-stubs: Use proper quoting for jovian log spew
  pkgs/jovian-stubs/dmidecode
  pkgs/jovian-stubs/sudo
Labels: 2. priority: 3. low, 2. topic: Bespoke stuff

#436 modules/steamos: Also enable bluetooth
  modules/steamos/bluetooth.nix
Labels: 1. type: bug, 2. priority: 2. normal, 2. topic: system integration
